### ISSUE TITLE
Blocks containing Chinese are not aligned with others

### ISSUE THREAD

**Issue by GNUqb114514** [MaxVerevkin/i3bar-river#40]
If a block contains Chinese, then the baseline of texts of this block is not aligned with other blocks.

![Screenshot](https://github.com/user-attachments/assets/9cee6752-be5d-40f3-b4d7-6c37cdddd47c)

Configurations:

`i3bar-river`:

```toml
command = "i3status-rs config-default.toml"

font = "monospace 12"
height = 30

# Tokyonight theme
background = "#24283bff"
color = "#c0caf5ff"
separator = "#ff9e64ff"
```

`i3status-rust`:

```toml
[[block]]
block = "custom"
command = "nix shell nixpkgs#python313 --command python3 /nix/store/91dlf5fq3a5b99vdk46qhcf9871lmp82-get-fcitx-im-label.py"
interval = "once"
signal = 4

[[block]]
block = "custom"
command = "sleep 1 && niri msg -j focused-window | jq 'if .==null then halt elif .app_id==\"Alacritty\" and (.title | test(\"^\\\\d+ --client-id \\\\d+ - \\\\(term://.+//\\\\d+:yazi .+ --chooser-file .+\\\\) - NVIM$\")) then \"Yazi on NVIM\" elif .app_id==\"firefox\" then \"Firefox\" else .title end' -r"
hide_when_empty = true
interval = 3

[[block]]
alert = 10.0
block = "disk_space"
info_type = "available"
interval = 60
path = "/"
warning = 20.0

[[block]]
block = "memory"
format = " $icon $mem_used_percents "
format_alt = " $icon swap $swap_used_percents "

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
format = " $icon $1m "
interval = 1

[[block]]
block = "sound"

[[block]]
block = "time"
format = " $timestamp.datetime(f:'%a %d/%m %R') "
interval = 60

[icons]
icons = "material-nf"

[theme]
theme = "native"
```
